<?php

use Drupal\Core\Template\Attribute;
use Drupal\share_tabs\Entity\ShareTab;

/**
 * Implements hook_theme().
 */
function share_tabs_theme($existing, $type, $theme, $path) {
  return [
    'share_tabs' => [
      'variables' => [
        'share_tab' => NULL,
      ],
    ],
  ];
}

function template_preprocess_share_tabs(&$variables) {
  /** @var \Drupal\share_tabs\Entity\ShareTab */
  $share_tab = $variables['share_tab'];

  $share_method = $share_tab->getShareMethod();
  $query_param_name = $share_tab->getQueryParamterName();
  $query_param = Drupal::request()->query->get($query_param_name);

  $tabs = [];
  $active_tab_set = FALSE;
  foreach ($share_tab->getTabs() as $key => $tab) {
    $entity_storage = \Drupal::entityTypeManager()->getStorage($tab['entity']['type']);
    $entity = $entity_storage->load($tab['entity']['id']);

    if (!$entity->access('view')) {
      // Don't show this tab as user don't has access to view it.
      continue;
    }

    if ($tab['name']['autogenerate']) {
      $module_handler = \Drupal::service('module_handler');
      if ($module_handler->moduleExists('pathauto')) {
        $name = \Drupal::service('pathauto.alias_cleaner')->cleanString($tab['title']);
      }
      else {
        $name = preg_replace('/[^a-zA-Z0-9\']/', '-', $tab['title']);
      }
    }
    else {
      $name = $tab['name']['custom'];
    }

    $anchor = $name;
    $tab_link_attributes = new Attribute();
    $tab_link_attributes['class'] = ['tablink'];
    if ($share_method == ShareTab::SHARE_METHOD_FRAGMENT) {
      $tab_link_attributes['href'] = '#' . $anchor;
    }
    else {
      if ($share_tab->getEmptyFragment()) {
        $tab_link_attributes['href'] = '#';
      }
    }

    if ($share_method == ShareTab::SHARE_METHOD_QUERY && $query_param == $name) {
      $tab_link_attributes->addClass('active-tab');
      $active_tab_set = TRUE;
    }

    $tab_link_attributes['data-tab-name'] = $name;
    $tab_link_attributes['role'] = 'button';

    $content_attributes = new Attribute();
    $content_attributes['class'] = ['tab-content'];
    $content_attributes['id'] = 'st-' . $anchor;
    $content_attributes['data-tab-name'] = $name;

    $content = NULL;
    if (!$tab_link_attributes->hasClass('active-tab')) {
      $content_attributes['style'] = 'display: none';
      if ($tab['ajax']) {
        $content_attributes['data-ajax-params'] = json_encode($tab['entity']);
        $content_attributes['data-ajax-loaded'] = 0;
        $content_attributes['aria-live'] = 'polite';
        $content = '';
      }
    }

    $view_mode = !empty($tab['entity']['view_mode']) ? $tab['entity']['view_mode'] : 'full';

    $content_attributes['data-ajax'] = $tab['ajax'];

    if (!isset($content)) {
      $content = $share_tab->renderTabContent($key);
    }
    $tabs[$key] = [
      'key' => $key,
      'name' => $name,
      'title' => $tab['title'],
      'link_attributes' => $tab_link_attributes,
      'content' => $content,
      'content_attributes' => $content_attributes,
    ];
  }

  if (!$active_tab_set) {
    foreach ($tabs as &$tab) {
      if ($share_tab->getDefaultTab() == $tab['key']) {
        $tab['link_attributes']->addClass('active-tab');
        $tab['content_attributes']['style'] = '';
        if (empty($tab['content'])) {
          $tab['content'] = $content = $share_tab->renderTabContent($tab['key']);
          $tab['content_attributes']['data-ajax-loaded'] = 1;
        }
      }
    }
  }

  $attributes = new Attribute();
  $attributes['data-share-method'] = $share_method;
  $attributes['data-query-param-name'] = $query_param_name;
  $attributes->addClass('share-tabs');
  $variables['tabs'] = $tabs;
  $variables['attributes'] = $attributes;
}

/**
 * Implements hook_block_view_alter().
 *
 * Alters the render array of specific blocks.
 */
function share_tabs_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // Get the block ID.
  $block_id = $block->getPluginId();

  // Check for a social sharing block.
  if ($block_id === 'social_sharing_block') {
    $build['#attached']['library'][] = 'share_tabs/dynamic_social_media_links';
  }
}
