<?php

use Drupal\Core\Template\Attribute;
use Drupal\share_tabs\Entity\ShareTab;

/**
 * Implements hook_theme().
 */
function share_tabs_theme($existing, $type, $theme, $path) {
  return [
    'share_tabs' => [
      'variables' => [
        'share_tab' => NULL,
      ],
    ],
  ];
}

function template_preprocess_share_tabs(&$variables) {
  /** @var \Drupal\share_tabs\Entity\ShareTab */
  $share_tab = $variables['share_tab'];

  $share_method = $share_tab->getShareMethod();
  $query_param = Drupal::request()->query->get('st');

  $tabs = [];
  $active_tab_set = FALSE;
  foreach ($share_tab->getTabs() as $key => $tab) {
    $entity_storage = \Drupal::entityTypeManager()->getStorage($tab['entity']['type']);
    $entity = $entity_storage->load($tab['entity']['id']);

    $anchor = 'st-' . $key;
    $tab_link_attributes = new Attribute();
    $tab_link_attributes['class'] = ['tablink'];
    if ($share_method == ShareTab::SHARE_METHOD_HASH) {
      $tab_link_attributes['href'] = '#' + $anchor;
    }
    else {
      $tab_link_attributes['href'] = '#';
    }

    if ($share_method == ShareTab::SHARE_METHOD_QUERY && $query_param == $key) {
      $tab_link_attributes->addClass('active-tab');
      $active_tab_set = TRUE;
    }

    $tab_link_attributes['data-tab-key'] = $key;

    $content_attributes = new Attribute();
    $content_attributes['class'] = ['tab-content'];
    $content_attributes['id'] = $anchor;
    $content_attributes['data-tab-key'] = $key;

    if (!$tab_link_attributes->hasClass('active-tab')) {
      $content_attributes['style'] = 'display: none';
    }

    $tabs[$key] = [
      'key' => $key,
      'title' => $tab['title'],
      'link_attributes' => $tab_link_attributes,
      'content' => \Drupal::entityTypeManager()
        ->getViewBuilder($tab['entity']['type'])
        ->view($entity, 'full'),
      'content_attributes' => $content_attributes,
    ];
  }

  if (!$active_tab_set) {
    foreach ($tabs as &$tab)
    if ($share_tab->getDefaultTab() == $tab['key']) {
      $tab['link_attributes']->addClass('active-tab');
      $tab['link_attributes']['style'] = '';
    }
  }

  $attributes = new Attribute();
  $attributes['data-share-method'] = $share_method;
  $attributes->addClass('share-tab');
  $variables['tabs'] = $tabs;
  $variables['attributes'] = $attributes;
}
